{% set name = "graphene" %}
{% set version = "2.1" %}
{% set sha256 = "cf8c7fd4dc74c959a44cd817d9e1b07abad185bbf586aac1f75650c1abdd5d31" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - six >=1.10.0,<2
    - graphql-core >=2.0,<3
    - graphql-relay >=0.4.5,<1
    - promise >=2.1,<3
    - aniso8601 >=3,<4

test:
  # TODO: restore when snapshottest available
  # requires:
  #   - coveralls
  #   - iso8601
  #   - mock  # [py27]
  #   - pytest
  #   - pytest-benchmark
  #   - pytest-cov
  #   - pytest-mock
  #   - pytz
  #   - six
  #   - snapshottest
  imports:
    - graphene
    - graphene.pyutils
    - graphene.relay
    - graphene.test
    - graphene.types
    - graphene.utils
  # commands:
  #   - python -m pytest graphene


about:
  home: http://graphene-python.org/
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  license: MIT
  license_family: MIT
  summary: 'GraphQL Framework for Python'
  dev_url: https://github.com/graphql-python/graphene
  doc_url: http://docs.graphene-python.org/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
    - bollwyvl
